# [default_session]
# name = "home"
# path = "~"

[[session]]
name = "tmux"
path = "~/dotfiles/tmux/.config/tmux/"
startup_command = "nvim tmux.conf"
# preview_command = "bat --color=always ~/dotfiles/tmux/.config/tmux/tmux.conf"

[[session]]
name = "bash"
path = "~/dotfiles/bash/"
startup_command = "nvim .bashrc"
# preview_command = "bat --color=always ~/dotfiles/tmux/.config/tmux/tmux.conf"

[[session]]
name = "nvim"
path = "~/dotfiles/nvim/.config/nvim/"
startup_command = "nvim"

[[session]]
name = "sesh"
path = "~/dotfiles/sesh/.config/sesh/"
startup_command = "nvim sesh.toml"

[[session]]
name = "dotfiles"
path = "~/dotfiles"
startup_command = "yazi"

# [[session]]
# name = "v5"
# path = "~/dotfiles/sesh/.config/sesh/"
# startup_command = "nvim sesh.toml"
#
# [[session]]
# name = "sesh"
# path = "~/dotfiles/sesh/.config/sesh/"
# startup_command = "nvim sesh.toml"
